### PR TITLE
Headless Server For Linux

### PR DESCRIPTION
**Pull request by s1nisteR**
The server module(only) has been modified to run headless in Linux.

### CODE REVIEW

**Comment by werkamsus** [comment]
Thanks for your contribution! The AppVeyor build seems to fail, but I will merge the pull req. into the linux branch. Will try it out myself soon!

**Comment by s1nisteR** [comment]
Ye looks like it’s missing the solution file and thus appveyor failed to build it. It might still have minor hitches here and there but for the most part, worked just fine. Hoping to collaborate with you on it further. 😊

**Comment by werkamsus** [comment]
Great! I've built the foundation a while ago as a hobby project and can't
contribute that much on my own, but if I see more traction in it I can
build a web GUI ontop in laravel :)
Do you have ideas on what you want to integrate to develop it further?

Best regards!

**Comment by s1nisteR** [comment]
Next step could be to add more functionality like file upload and download,
some sort of directory traversal feature but prolly the most exciting stuff
would be to bypass AV detection. Perhaps some features taken from sevagas
blogs; they are filled with new ways to bypass static and dynamic AV
analysis. :)

**Comment by werkamsus** [comment]
Amazing, let me know when there's something to take a look at :)

**Comment by werkamsus** [comment]
@s1nisteR could you also do me a favor and get the AppVeyor build to succeed again? Thanks!

**Comment by s1nisteR** [comment]
Hey, I built the Server project only in Linux so it's missing the solution
file. But the problem is some days ago I had a data loss on my HDD and
unfortunately had to reinstall Ubuntu WSL and thus lost the project files.
I had pushed to github before so you just need to add a simple CMakeLists
file with the names of the .cpp files and it will compile just fine.

**Pull request merged**
